version: "3.8"

services:
  fastapi:
    build: app/
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./app/db:/app/db

volumes:
  app:
